language: java

jdk: oraclejdk8

sudo: required

services:
- docker

env:
  global:
  - secure: jsYmVKXKliZLBeA0bUyyEBAg8GVd6qBJE3xHIM0YWlBMlYPR1SBqduUMgUbVXNrmYdjn3cr6kCAm43DS6nLK2pGLvbBBEQlBs8t+mxrnHTQKmpLkqrX3S0U2p7rm7vMVQ/t9kC4Wcgwmt0iUBy0q1wcbeo00wJ0AYKN6gD+ZYeglqlhGbubyY8XoZWGpcv2CmvHmnJSJuVwHQ34CaxldCLlqe4opHu4HOFnrIofs3bDOAgTyttL7Ij2533iIAack2glkFOd1WpmgYPiAD+RBM/G1i4due3qAwmy2sPcKHIuxWQGsabgnfGbc5COSWEyvnEsTLBWtG611nym+AoIWS+8YWMNV8Zscad/tgwyT3wHBFzKA+NQcBehFwZDjXCIciGs1ELLagnKhDBAMHlDniMq9NDYVC2Yg8k+UyjBYrd98P3x/7/UhG6RZepJEBY0Fm06Kkwz39PhuLb+iQTWKHd3h2kJ5r9n8/1mqqrEJb63WENQ2VXU+x9TD37mrOoi371WyvENiqIYtlkptRTYQjeDFb92qncNYKIdQf6VerY00f1AxpcQY2yQnHFSDY0P0JsQoymdPIiDW+obNRSivmPoHoS2GIqCS70CKgqqHFB4ya2bEGhlN9WhkpbX59PZZreKZrrPatGDRfIpgbQV3fFvzaUsEqk6Yv1oIbzVEUuQ=
  - secure: PSZZs6EmQQPdIuaf4dAE+yciKBh4Dp8kHL1+Z2EDan8tsCMFO7jqImEdmFxzno1ev4oa/OnZtLgu1MS5EL0jHlECL2pAQEQ0p8D2dDl7oYkLJALD323yr1d8Cir4ugnxITaU6asLXDYB5MffIote4V+pg3H1oxVkZUh0Dqf34+WogfLhdAuqeKse5KjhnTxtZpMFyjW6SArKgv7qb4LXl+lEdMntFH8KYr1/YnyyRLZmYRUbtldh4j7nxc7LohLQ4JzsKbACFduRNidUSo+1fB/ln5IXUdS5zu57SwX+gsqpYdvpA1mdjbuqxMdMV1tlKBFpK76PcR2RBN3MSQ2AAnvoxO2d4cD0y3Q2Ytl2L64wlkCL5Z/78bnh7f196/tG4FcHe59hkbXmWa3p9W3BYKczK7Re0bBPtXG7Yyjlhdtp/lSV6zDVwPeh3aM09wS6m2gqZe/7X9tVsLdJbYvzqtIjw+jSRbYR1PN4ZY5g+SXMUN5ahhrFaJ0AbkhnFpkiEJi8bf3zh+lCf6RtaTANPQKzCqvpRCa540O4d9LN3QXJkg2Vt7B2Iyks4gjF8wNTNEFV5H/Tu4SLOrKsk/1doxRkTjKbp2aDS0n7NZQHR2L/vqPNoDle9LcTBsrkpN2vn7yzXnZevwUVdT4Frdm59+fMYgZltifipxPj2lunKt4=
  - secure: lLcD+Gh0k/YMAF3mjvpPUVdWRA977SOdMYASA943OCk58spzib6tx4MfbCR0wIKGBv4z3AVKA6brNO7qHJlj2PMzpqxhW4LBPY58N4jYluDy+4pDmWUdBsxe+oS8n0QPXRNqbcZtLllVT6K2NV1fMhFeyT6gqzRbEt56kDut2diOqJ8QNDAAh5z+PPy9SqH9qSxgZU/P/QTaT01RmVsLUgaks1VtH6H6FnzamvvZt0VNNwL9PhGHUOy5nSfsxpMElWt4kTc26Qph+q9rXUk+0JZFnXZhAfkLMWfBb/3YhJGKQuNHp2tdpJVzK1nUuWxf68SHYDaZJDzqhPSI9G4RuXy/sjPCGsiy6BVT1Q2b/ZE+UJkQDvPSaF9Le8HXiBZxYQWPaqHcgTa7NQDshsljPuDn/+zb/M/TkVo4HjehdUW0iwqps31RxkPvxbDA6SRgE5BDmDdIzC2xqxMlLvjpsbmtsFCVR1ksIOso2l3WUMVqKcy5AfQhRzb98WXVsAkac/gOanVYI+4L+60LHB2H7ZFWApuU8INgqvC0DUZNnTqVnEzs6C8nm0pwljdmHteMzx/GFRw6xZM9sY/877GQu90qbqvHRei9JPLP3zKa85vbnU0jf53G5lGYudEyZs5wP0bgPR3R+LItTwXeJpprI19lo3JPkKL2/lKvAEbWveg=

script:
- mvn clean package
- docker build -t 50shadesoftelegram/telegrambot --build-arg BOT_API_KEY=$BOT_API_KEY .

deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    branch: master
