language: java
dist: trusty
jdk: openjdk8

sudo: required

services:
- docker

env:
  global:
  - secure: jsYmVKXKliZLBeA0bUyyEBAg8GVd6qBJE3xHIM0YWlBMlYPR1SBqduUMgUbVXNrmYdjn3cr6kCAm43DS6nLK2pGLvbBBEQlBs8t+mxrnHTQKmpLkqrX3S0U2p7rm7vMVQ/t9kC4Wcgwmt0iUBy0q1wcbeo00wJ0AYKN6gD+ZYeglqlhGbubyY8XoZWGpcv2CmvHmnJSJuVwHQ34CaxldCLlqe4opHu4HOFnrIofs3bDOAgTyttL7Ij2533iIAack2glkFOd1WpmgYPiAD+RBM/G1i4due3qAwmy2sPcKHIuxWQGsabgnfGbc5COSWEyvnEsTLBWtG611nym+AoIWS+8YWMNV8Zscad/tgwyT3wHBFzKA+NQcBehFwZDjXCIciGs1ELLagnKhDBAMHlDniMq9NDYVC2Yg8k+UyjBYrd98P3x/7/UhG6RZepJEBY0Fm06Kkwz39PhuLb+iQTWKHd3h2kJ5r9n8/1mqqrEJb63WENQ2VXU+x9TD37mrOoi371WyvENiqIYtlkptRTYQjeDFb92qncNYKIdQf6VerY00f1AxpcQY2yQnHFSDY0P0JsQoymdPIiDW+obNRSivmPoHoS2GIqCS70CKgqqHFB4ya2bEGhlN9WhkpbX59PZZreKZrrPatGDRfIpgbQV3fFvzaUsEqk6Yv1oIbzVEUuQ=
  - secure: ti1Zfsyd/icrHFe2kfUfe1eVyB2WOYK2ZCIh4Ym4n7kOvObgMVRqdsWAH/xzzVPz+aGcNoZQfDcC4EXCtuZUMAM0I32ieAJQje2qYRQOBceGhJ5P1w6FwzM8FMiFnMSReLsX8OW+lUT9GuAZzoSH9P4CRXRWmdIqONiwGGLi5PZXG0nyjqpg7xnjwbhB/2WhfBf5CaoFHnx7IsXFa36MBvtUfeZ9HweOXoXQjtqub8WTlp6FfWRCWOOSEj6J7O/Wx0enkQeYlXcOysofxlea+p9e2p/pus7Ae64cLjufIrecDRS/PHlhnyL6DokCvsacTmxMmddYMH9pFYN9v26ASPgZIErjfafvQhF6V7f2ZAk6eOaDVtaSLo4y1GmjCEWptTPEv88rWq+A9z+khYrJer+lLjtLyk72v0G8C4y0mDDBFWcienKHRaQIajFtVlHgBh+q+gVv1SyeFu2cgNvck6iSNySof/QMoCKShD1vM2ddB1GED/vN8qwRYoi7NIkOYiKe+tzavanU8HYlqve/AVW2mODXSEIB6v6CbQRzIJNFkFaPY5orQf7cuPwjDuQFrnHjgqF32EgQpDTxgQJEmO3p/nZ7vj3htS2V/rHyIwJQL1tCBFPX5fSpz01vOWhV1bDzUzzDSQVSvMXOfMdrv6cmSaqO//7khj146wmH4aQ=

cache:
  directories:
  - "$HOME/.m2"

script:
- mvn clean package
- docker build -t 50shadesoftelegram/telegrambot .

deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    branch: master
