name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - uses: whelk-io/maven-settings-xml-action@v4
      with:
        repositories: '[{ "id": "gh-jtelegram", "url": "https://maven.pkg.github.com/jTelegram/jTelegramBotAPI" }]'
        server: '[{ "id": "gh-jtelegram", "username": "example", "password": "${{ secrets.GITHUB_TOKEN }}" }]'
        
    - name: Setup Maven
      uses: stCarolas/setup-maven@v1
    
    - name: Build project
      run: mvn clean package

    - uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 50shadesoftelegram/telegrambot

    - name: Push to DockerHub
      run: docker push 50shadesoftelegram/telegrambot
